name: Main-Test-GitOps
on:
  workflow_dispatch:

jobs:
  build-deploy:
    name: Main-Build-GitOps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: paulhatch/semantic-version@v5.0.0-alpha
        id: version
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "(MAJOR)"
          # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
          minor_pattern: "(MINOR)"
          # A string to determine the format of the version output
          version_format: "${major}.${minor}.${patch}-rc${increment}"
          # Optional path to check for changes. If any changes are detected in the path the
          change_path: "src"
          # 'changed' output will true. Enter multiple paths separated by spaces.
          # If true, the body of commits will also be searched for major/minor patterns to determine the version type.
          search_commit_body: true
          namespace: novata-slack-bolt-app
          # The output method used to generate list of users, 'csv' or 'json'.
    
      - uses: engineerd/configurator@v0.0.8
        with:
          name: octopilot
          fromGitHubReleases: "true"
          repo: "dailymotion-oss/octopilot"
          version: "v1.1.4"
          urlTemplate: "https://github.com/dailymotion-oss/octopilot/releases/download/{{version}}/octopilot_1.1.4_linux_amd64"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Testing
        env:
          VERSION_TAG: ${{ steps.version.outputs.version_tag }}
          VERSION: ${{ steps.version.outputs.version}}
        run: |
         echo steps.version.outputs.version_tag  $TAG
         echo steps.version.outputs.version $VERSION
#       - uses: robinraju/release-downloader@v1.5
#         with:
#           repository: "dailymotion-oss/octopilot"
#           tag: " v1.1.4"
#           fileName: "octopilot_1.1.4_linux_amd64"
#       - name: run octopilot
#         run: octopilot_1.1.4_linux_amd64
          
